version: "2"

services:

  mhp-desk-booking-database:
    image: postgres:15.3
    container_name: mhp-desk-booking-database
    restart: unless-stopped
    hostname: mhp-desk-booking-db
    environment:
      - POSTGRES_DB=mhp-desk-booking
      - POSTGRES_USER=mhp-desk-booking
      - POSTGRES_PASSWORD=12345678
    volumes:
      - mhp-desk-booking-database:/var/lib/postgresql/data
    networks:
      - mhp-desk-booking-default

  mhp-desk-booking-backend:
    image: mhp-desk-booking-backend
    container_name: mhp-desk-booking-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILE=docker
      - DB_HOST=mhp-desk-booking-db
      - DB_PORT=5432
      - DB_SCHEMA=mhp-desk-booking
      - DB_USERNAME=mhp-desk-booking
      - DB_PASSWORD=12345678
    networks:
      - mhp-desk-booking-default
    ports:
      - "8080:8080"
networks:
  mhp-desk-booking-default:
  portainer_default:
    external: true

volumes:
  mhp-desk-booking-database:
